http:
  host: '0.0.0.0'
  port: 3000

server:
  # host: &host '192.168.3.198'
   host: &host 'localhost'

mysql:
  host: *host
  port: 3306
  username: 'root'
  password: '123456'
  database: 'chat_db'

redis:
  host: *host
  port: 6379
  auth_pass: '123456'
  db: 0
  ttl: 0

file:
  fileSizeLimit: 1024 * 1024
